// import Head from 'next/head'
// import { Inter } from '@next/font/google'

// import handler from "./api/auth/signin";
// import SigninPage from "./auth/signin";

// const inter = Inter({ subsets: ['latin'] })

// export default function Home() {
//     return (
//         <>
//             <Head>
//                 <title>Emilie MONTPRE</title>
//                 <meta name="description" content="Generated by Emilie MONTPRE"/>
//                 <meta name="viewport" content="width=device-width, initial-scale=1"/>
//                 <link rel="stylesheet" href="/styles /globals.css" />
//                 {/* <link rel="preconnect" href="https://fonts.googleapis.com">
//                 <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
//                 <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500&display=swap" rel="stylesheet"> */}
//                 <link rel="icon" href="/favicon.ico" />
//             </Head>
//             <main>
//                 <h1>Hello World !</h1>
//                 <section>
//                     <div>
//                         <form action="">
//                             <label htmlFor="email">Email</label>
//                             <input type="email" />

//                             <label htmlFor="password">Password</label>
//                             <input type="text" name="passeword" />

//                             <button type="submit">Connect</button>
//                         </form>
//                     </div>
//                 </section>
//             </main>
//         </>
//     )
// }

import Head from 'next/head'

import { Navigation, Footer } from "./components/Nav";
import ContactForm from "./components/contact-component";
import Reseaux from './components/Reseaux';

import { Inter } from '@next/font/google'
import Link from "next/link"
import NextAuth from './api/auth/[...nextauth]';

const interRegular = Inter({ 
    weight: ['400'],
    subsets: ['latin'] })

export default function Home() {
    return (
        <>
            <Head>
                <title>Emilie MONTPRE</title>
                <meta name="description" content="Generated by Emilie MONTPRE"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="stylesheet" href="/styles /globals.css" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navigation/>
            <main className='h-full'>
            <section className="px-4 py-8 lg:px-8 lg:py-12 bg-gray-100">
  <div className="mx-auto max-w-7xl">
    <h2 className="text-3xl font-bold text-gray-900">Titre de la section</h2>
    <p className="mt-4 text-gray-500">Texte de la section</p>
  </div>
</section>


                {/* <NextAuth></NextAuth> */}
                <ContactForm />
            </main>
            <Footer/>
            <Link rel="stylesheet" href="http://localhost:3000/admin/works" />
        </>
    )
}