import Head from 'next/head'
import { Inter } from '@next/font/google'

import handler from "./api/auth/signin";
import SigninPage from "./auth/signin";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    return (
        <>
            <Head>
                <title>Emilie MONTPRE</title>
                <meta name="description" content="Generated by Emilie MONTPRE"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="stylesheet" href="/styles /globals.css" />
                {/* <link rel="preconnect" href="https://fonts.googleapis.com">
                <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
                <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500&display=swap" rel="stylesheet"> */}
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1>Hello World !</h1>
                <section>
                    <div>
                        <form action="">
                            <label htmlFor="email">Email</label>
                            <input type="email" />

                            <label htmlFor="password">Password</label>
                            <input type="text" name="passeword" />

                            <button type="submit">Connect</button>
                        </form>
                    </div>
                </section>
            </main>
        </>
    )
}